provider: oci
vector_store: oci

oci:
  endpoint: ${OCI_GENAI_ENDPOINT}
  region: ${OCI_REGION}
  compartment_id: ${OCI_COMPARTMENT_OCID}
  auth_mode: ${OCI_AUTH_MODE}          # config_file | instance_principal
  config_path: ${OCI_CONFIG_PATH}
  config_profile: ${OCI_CONFIG_PROFILE}
  models:
    embeddings: ${OCI_EMBED_MODEL_ID}  # cohere.embed-english-v3.0
    chat: ${OCI_LLM_MODEL_ID}          # cohere.command-english-v3.0

  # model_id may be either a public alias (e.g., cohere.command-english-v3.0)
  # or an OCID (ocid1.generativeaimodel...). The loader normalizes both into model_id.
  embeddings:
    model_id: ${OCI_EMBED_MODEL_ID}
    # model_ocid: <deprecated, use model_id instead>
    endpoint: ${OCI_GENAI_ENDPOINT}
    compartment_id: ${OCI_COMPARTMENT_OCID}
    auth_file: ${OCI_CONFIG_PATH}
    auth_profile: ${OCI_CONFIG_PROFILE}

  # For primary LLM, aliases work with LangChain; OCID triggers native OCI text path.
  llm_primary:
    model_id: ${OCI_LLM_PRIMARY_MODEL_ID}
    # model_ocid: ${OCI_LLM_PRIMARY_MODEL_OCID}  # deprecated, use model_id instead
    endpoint: ${OCI_LLM_PRIMARY_ENDPOINT}
    compartment_id: ${OCI_LLM_PRIMARY_COMPARTMENT_OCID}
    auth_file: ${OCI_CONFIG_PATH}
    auth_profile: ${OCI_CONFIG_PROFILE}
    # Optional generation parameters (can also be overridden by env):
    max_tokens: ${OCI_LLM_PRIMARY_MAX_TOKENS}
    temperature: ${OCI_LLM_PRIMARY_TEMPERATURE}
    top_p: ${OCI_LLM_PRIMARY_TOP_P}
    top_k: ${OCI_LLM_PRIMARY_TOP_K}
    frequency_penalty: ${OCI_LLM_PRIMARY_FREQUENCY_PENALTY}
    presence_penalty: ${OCI_LLM_PRIMARY_PRESENCE_PENALTY}

  # Fallback chat adapter requires a model OCID (aliases unsupported).
  llm_fallback:
    model_id: ${OCI_LLM_FALLBACK_MODEL_ID}
    # model_ocid: ${OCI_LLM_FALLBACK_MODEL_OCID}  # deprecated, use model_id instead
    endpoint: ${OCI_LLM_FALLBACK_ENDPOINT}
    compartment_id: ${OCI_LLM_FALLBACK_COMPARTMENT_OCID}
    auth_file: ${OCI_CONFIG_PATH}
    auth_profile: ${OCI_CONFIG_PROFILE}
    # Optional generation parameters (can also be overridden by env):
    max_tokens: ${OCI_LLM_FALLBACK_MAX_TOKENS}
    temperature: ${OCI_LLM_FALLBACK_TEMPERATURE}
    top_p: ${OCI_LLM_FALLBACK_TOP_P}
    top_k: ${OCI_LLM_FALLBACK_TOP_K}
    frequency_penalty: ${OCI_LLM_FALLBACK_FREQUENCY_PENALTY}
    presence_penalty: ${OCI_LLM_FALLBACK_PRESENCE_PENALTY}

oraclevs:
  dsn: ${DB_DSN}                       # 10.0.0.3:1529/FREEPDB1
  user: ${DB_USER}                     # sys
  password: ${DB_PASSWORD}
  table: ${ORACLEVS_TABLE}             # MY_DEMO
  distance: dot_product
